[package]
name = "vos"
version = "0.1.0"
authors = ["yu"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

#[lib]
#crate-type = ["staticlib"]

[dependencies]
fdt = "0.1.4"
log = "0.4"
